apiVersion: v1
kind: ConfigMap
metadata:
  name: pedido-config
data:
  spring.datasource.url: "jdbc:mariadb://${SPRING_DATASOURCE_URL}/lanchonetedb?createDatabaseIfNotExist=true"
  spring.datasource.db-name: ${SPRING_DATASOURCE_NAME}
  spring.datasource.username: ${SPRING_DATASOURCE_USERNAME}
  spring.profiles.active: ${SPRING_ACTIVE_PROFILE}
  services.produto.url: ${SERVICE_URL_PRODUTO}
